name: pinball_flame
description: Set of out-of-the-way solutions for common Pinball game problems.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.1.3
  flame: ^1.16.0
  flame_bloc: ^1.11.0
  flame_forge2d: ^0.17.0
  flutter:
    sdk: flutter
  geometry:
    path: ../geometry

dev_dependencies:
  flame_test: ^1.16.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
